Ticket2764 create ioc generator
ISISComputingGroup/IBEX_device_generator pull request #1
Opened 2017-11-23 14:08 UTC by AdrianPotter

Create a device from scratch. Includes:

- OPI
- Support submodule
- IOC
- Emulator
- IOC tests

2017-11-27 10:19 UTC, Tom-Willemsen requested changes
Looks like it's mostly there.

Launching the IOC I get a couple of weird errors:

```
Warning: IOC is booting with TOP = "C:\Instrument\Apps\EPICS\support\EPICS_V4\master\"
          but was built with TOP = "C:/Instrument/Apps/EPICS/ioc/master/ADRIAN"
```

and

```
No such file or directory dbRead opening file ../../db/ADRIAN-IOC-01.db
```

(it's substituted in the wrong name for the DB file)

I also noticed a couple of things which would be nice to do, but don't *have* to be done if they're hard:

- The st.cmd is missing a `epicsEnvSet "STREAM_PROTOCOL_PATH" "$(AMINT2L)/data"` line
- The support module is not built
- Makefile entry not added in ioc directory (to long list of DIRS_TO_BUILD). It looks like there is logic for this?
- Makefile entry not added to support directory, it also looks like there was logic for this?

Finally,
- Could you add a wiki page about it describing how to use it, what it does for you, and what it doesn't do for you
- Could you add release notes

2017-11-27 10:19 UTC, Tom-Willemsen commented on utils/git_utils.py
> +                    self._repo.git.clean(f=True, d=True)
I'm still hesitant to let the user do a `clean` and `reset`... I wonder if `git stash --include-untracked` would be sufficient here? The advantages that I can see are (1) it doesn't touch ignored (i.e. built) files and (2) it is reversible if the user makes a mistake.

2017-11-27 16:25 UTC, AdrianPotter commented
- I've added a more interactive selection of the branch cleaning option. The choice you suggested is now available. The existing choices remain but have explicit implications attached to them and you have to do an extra level of confirmation after selecting them.

2017-11-27 17:50 UTC, AdrianPotter commented
https://github.com/ISISComputingGroup/EPICS-ioc/tree/Ticket9005_Add_IOC_ADRIAN
https://github.com/ISISComputingGroup/EPICS/tree/Ticket9005_Add_IOC_ADRIAN
https://github.com/ISISComputingGroup/EPICS-Adrian/tree/Ticket9005_Add_IOC_ADRIAN
https://github.com/ISISComputingGroup/ibex_gui/tree/Ticket9005_Add_IOC_ADRIAN
https://github.com/ISISComputingGroup/EPICS-DeviceEmulator/tree/Ticket9005_Add_IOC_ADRIAN
https://github.com/ISISComputingGroup/EPICS-IOC_TestFramework/tree/Ticket9005_Add_IOC_ADRIAN

2017-11-27 17:52 UTC, AdrianPotter commented
[ADRIAN_01-20171127.log](https://github.com/ISISComputingGroup/IBEX_device_generator/files/1506967/ADRIAN_01-20171127.log)

2017-11-28 11:12 UTC, Tom-Willemsen approved these changes

2017-11-28 11:12 UTC, merged